# Generated by Django 4.2 on 2023-07-17 06:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_aboutme'),
    ]

    operations = [
        migrations.CreateModel(
            name='Graduation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('degree_name', models.CharField(max_length=30)),
                ('university_name', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('desc', models.TextField()),
            ],
        ),
    ]
