# Generated by Django 4.2 on 2023-07-18 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='sent_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
